services:

  # The main microservice, serving the x-language-search.lo-res.org site
  #
  x-language-search:
    image: x-language-search:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    environment:
      PYTHONPATH: /:/app
    env_file: .env
    ports:
      - "9991:9991"
    dns: 8.8.8.8
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x-language-search.rule=Host(`x-language-search.lo-res.org`)"
      - "traefik.http.routers.x-language-search.entrypoints=websecure"
      - "traefik.http.routers.x-language-search.tls.certresolver=myresolver"
      - "traefik.http.services.x-language-search.loadbalancer.server.port=9991"
    #network_mode: host
    volumes:
      - ./app:/app
      - ./chroma.db:/chroma.db
    networks: 
      - web

networks:
  web:
    external: true
